### ISSUE TITLE
Udokumentować endpointy

### ISSUE THREAD

**Issue by marpiech** [intelliseq/genetraps-opensource#18]
W ten sposób jest super
[https://gist.github.com/iros/3426278](https://gist.github.com/iros/3426278)
I dodać link do README dla każdego endpointu

**Comment by marpiech** [comment]
brakuje opisu mkdir

**Comment by Z-DNA** [comment]
Zamknać, czy zostawić otwarde dla bwa?

**Comment by marpiech** [comment]
Zamykam. Jak nię beðzie dla bwa to się otworzy
