### ISSUE TITLE
Ustalić system porządkowania plików i udokemntować

### ISSUE THREAD

**Issue by marpiech** [intelliseq/genetraps-opensource#19]

**Comment by marpiech** [comment]
Tak przypominam, że trzeba zrobić gdzieś specyfikację do tego

**Comment by marpiech** [comment]
Opis jest. Brakuje source'a do opisu

**Comment by Kaleeth** [comment]
Link do obrazka na google drive dodany. Podgląd publiczny. Edycja możliwa po otrzymaniu uprawnień.
