### ISSUE TITLE
Przerobić w tutorialu adres z resources na pliki z githuba

### ISSUE THREAD

**Issue by marpiech** [intelliseq/genetraps-opensource#30]
W tej linijce:
`U1ID=$(curl -X POST -H "Authorization: Bearer $TOKEN" "localhost:8086/upload?url=http://resources.intelliseq.pl/kamilant/test-data/fastq/capn3.1.fq.gz&tag=left&sampleNumber=$SAMPLE_NUMBER" | jq -r ".id")`

na githubie jest w test-data

**Comment by Kaleeth** [comment]
README zmodyfikowany, niech ktoś potwierdzi czy dobrze

**Comment by marpiech** [comment]
Nie jest dobrze. Fetch_url pobiera jakis html

**Comment by marpiech** [comment]
Jest git
