### ISSUE TITLE
Nowa aplikacja do podpięcia GATK g.vcf

### ISSUE THREAD

**Issue by marpiech** [intelliseq/genetraps-opensource#43]
dx run iseq_gatk_haplotype_caller -ibam="capn3.1.bam" -ireference="genetraps-resources:reference/grch38-no-alt/grch38-no-alt.tar" -ivcfs="genetraps-resources:vcf/Homo_sapiens_assembly38.dbsnp138.vcf" -iinterval="chr15:42377802-42397802"

bam
interval jest nieobowiązkowy
vcfs to array (może być kilka wpisów)

dla usera nic widocznego

**Comment by Kaleeth** [comment]
reference w properties
vcfs jako tablica (lub string) również w properties
interval jako zwykły string, reszta pliki
poprawić README dla /fastqc i /bwa (reference w properties i nie wprowadzany przez usera)
dodać prezentację struktury folderów i plików w samples do README (może być zdjęcie)
gatk...

**Comment by Kaleeth** [comment]
gatk podpięty więc zamykam
