### ISSUE TITLE
Brakuje endpointu hello w api-security

### ISSUE THREAD

**Issue by marpiech** [intelliseq/genetraps-opensource#44]
Load balancer sprawdzając czy mikroserwis żyje musi gdzieś pytać i sprawdza kod odpowiedzi. Standardowym sposobem jest wystawienie endpointu hello bez zabezpieczenia.

Pamiętac o teście JUnit sprawdzającym działanie endpointu

**Comment by marpiech** [comment]
To potrzebuję dość pilnie. Prosze o zwiekszenie priorytetu

**Comment by Kaleeth** [comment]
jest na developie

**Comment by marpiech** [comment]
Ha. I działa. Samo się wrzuciło
http://genetraps.intelliseq.pl:8088/hello
