### ISSUE TITLE
Test do gatk-haplotype-caller dla kilku vcf

### ISSUE THREAD

**Issue by Kaleeth** [intelliseq/genetraps-opensource#48]
By przetestować zczytywanie tablicy vcfs z properties

**Comment by marpiech** [comment]
w genetraps resources dodałem cztery pliki

Homo_sapiens_assembly38.known_indels.vcf
Homo_sapiens_assembly38.known_indels.vcf.gz
Mills_and_1000G_gold_standard.indels.hg38.vcf
Mills_and_1000G_gold_standard.indels.hg38.vcf.gz
Najpierw dodaj vcfy
A potem sprawdź czy zadziała wersja z vcf.gz

**Comment by marpiech** [comment]
Super. Zamykam
