### ISSUE TITLE
IMPORTANT: dodać zmienne STAGING_USERNAME i STAGING_USERNAME password

### ISSUE THREAD

**Issue by marpiech** [intelliseq/genetraps-opensource#50]
Brak zmiennych STAGING_USERNAME w zmiennych

**Comment by Z-DNA** [comment]
STAGING_USERNAME
STAGING_PASSWORD
STAGING_HASH

**Comment by Z-DNA** [comment]
curl --request POST \
  --url http://localhost:9999/oauth/token \
  --header 'authorization: Basic $STAGING_HASH' \
  --header 'content-type: application/x-www-form-urlencoded' \
  --data 'grant_type=password&username=$STAGING_USERNAME&password=$STAGING_PASSWORD'

STAGING_CLIENT_USERNAME i STAGING_CLIENT_PASSWORD zamiast HASH
