### ISSUE TITLE
Kontrola, że username to nie email, a email to email;

### ISSUE THREAD

**Issue by Z-DNA** [intelliseq/genetraps-opensource#57]
Przypinam to by pamiętać w kliencie, żeby username i email miały odpowiednie regexy, by nie daj boże ktoś próbował zarejestrować jako username czyjegoś maila. Czy serwer ma sprawdzać jakkolwiek te dane pod kątem innym niż tylko duplikat username/email?

**Comment by marpiech** [comment]
No w pewnym etapie oczywiście, że tak. COnfirmation email bedzie musiał być. Na razie zostawiamy, chyba, ze bedzie wolne

**Comment by marpiech** [comment]
Zamykam
