### ISSUE TITLE
Uruchomić fastq z wdl na aws

### ISSUE THREAD

**Issue by marpiech** [intelliseq/genetraps-opensource#84]
Uruchomienie wdla z fastqc. Potrzebne są inputy, które są w hello.inputs - jedynym inputem jest adres pliku fastq na S3. Główny wdl to hello.wdl. Mozesz nazwac odpowiednio i tasks.zip, który zawiera dependencies dla hello.wdl.

Tutaj jest swagger dla serwera: `http://ec2-100-25-40-253.compute-1.amazonaws.com`

[cromwell-pack.zip](https://github.com/intelliseq/genetraps-opensource/files/2874989/cromwell-pack.zip)
```
curl -X POST "http://ec2-100-25-40-253.compute-1.amazonaws.com/api/workflows/v1" -H "accept: application/json" -H "Content-Type: multipart/form-data" -F "workflowSource=@hello.wdl" -F "workflowInputs=@hello.inputs" -F "workflowType=WDL" -F workflowDependencies=@tasks.zip
```

**Comment by marpiech** [comment]
Zmiana curla na prostszy. Wystarczy dostarczyć hello.inputs
`curl -X POST "http://ec2-100-25-40-253.compute-1.amazonaws.com/api/workflows/v1" -H "accept: application/json" -H "Content-Type: multipart/form-data" -F "workflowUrl=https://raw.githubusercontent.com/intelliseq/public-workflows/master/wdl/workflows/quality-check/quality-check.wdl" -F "workflowInputs=@hello.inputs;type=" -F "workflowType=WDL"`

**Comment by marpiech** [comment]
### Nadanie `sampleid`
```
sampleid=260
fastq_file="s3://iseq-cromwell-results/data/282-chr15.47497301-49497301.HCK5LCCXY_L2_1.fq.gz"
```
### Uruchomienie joba
```
curl -X POST "http://ec2-100-25-40-253.compute-1.amazonaws.com/api/workflows/v1" -H "accept: application/json" -H "Content-Type: multipart/form-data" -F "workflowUrl=https://raw.githubusercontent.com/intelliseq/public-workflows/master/wdl/workflows/quality-check/quality-check.wdl" -F "workflowInputs={\"quality_check_workflow.fastqc.fastq\":\"$fastq_file\"}" -F "workflowType=WDL" -F "labels={\"sampleid\":\"$sampleid\"};type=application/json"
```
### Pobranie id
```
jobid=`curl -X GET "http://ec2-100-25-40-253.compute-1.amazonaws.com/api/workflows/v1/query?label=sampleid%3A$sampleid" -H "accept: application/json" | jq -r .results[0].id`
```
### Pobranie statusu
```
status=`curl -X GET "http://ec2-100-25-40-253.compute-1.amazonaws.com/api/workflows/v1/query?label=sampleid%3A$sampleid" -H "accept: application/json" | jq -r .results[0].status`
```
### Pobranie outputów jako json
```
curl -X GET "http://ec2-100-25-40-253.compute-1.amazonaws.com/api/workflows/v1/$jobid/outputs" -H "accept: application/json"
```

**Comment by marpiech** [comment]
Dalej myślę nad tym, żeby było prostsze w obsłudze. I chciałbym żeby był jeden endpoint do obsługi wdli, a  pytający daje request o uruchomienie wdla. Wtedy nie trzeba będzie robić tysięcy różnych endpointów do różnych analiz. Po stronie klienta podam nazwę wdla i inputy. 
Problemy do przemyślenia rozwiązania:
- gdzie podać informację o katalogu z wynikami?
- jak podać ściezki do inputów
- trzeba będzie zrobić endpoint listujący wdle i ich inputy

Dodaję Kamila do taska, zeby pomógł w przemyśleniach

**Comment by marpiech** [comment]
Ten daje succeed
```
curl -X POST "http://ec2-100-25-40-253.compute-1.amazonaws.com/api/workflows/v1" -H "accept: application/json" -H "Content-Type: multipart/form-data" -F "workflowUrl=https://gitlab.com/intelliseq/workflows/raw/master/src/main/wdl/tasks/print_input/print_input.1.wdl" -F "workflowInputs={\"print_input.print_input_file.name\":\"s3://iseq-cromwell-results/data/282-chr15.47497301-49497301.HCK5LCCXY_L2_1.fq.gz\"}" -F "workflowType=WDL" -F "labels={\"sampleid\":\"400\"};type=application/json"
{"id":"7825f223-e483-4c3f-b96a-86d7d4de7d76","status":"Submitted"}
```

**Comment by Kaleeth** [comment]
stare
